"""Owner-scoped metadata and opaque protected artifacts; never decrypts payloads."""
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
import sqlite3
import time
from typing import Literal
from uuid import UUID, uuid4
import shutil
import re

from fastapi import HTTPException
from pydantic import BaseModel, ConfigDict, Field, StrictInt, field_validator, model_validator, ValidationError

from backend.auth import VerifiedOwner
from backend.documents import LABELS

LEGACY_KINDS = frozenset({'source', 'manifest', 'output_pdf', 'output_docx', 'output_txt'})
KINDS = LEGACY_KINDS | {'filename'}
MAX_ARTIFACT = 64 * 1024 * 1024
MAX_DOCUMENT = 192 * 1024 * 1024
MAX_OWNER_DOCUMENTS = 100
DRAFT_TTL = 15 * 60
SCHEMA_VERSION = 1


class PublicReplacement(BaseModel):
    model_config = ConfigDict(extra='forbid')
    category: str = Field(max_length=32)
    occurrence: int = Field(strict=True, ge=1, le=200_000)
    replacement: str = Field(max_length=128)


class ReplacementProjection(BaseModel):
    model_config = ConfigDict(extra='forbid')
    replacements: list[PublicReplacement] = Field(max_length=200_000)


# Only values generated by our replacement templates may be retained in public
# review metadata. Originals, offsets and arbitrary user text are not accepted.
SYNTHETIC_PATTERNS = {
    'private_person': r'Alex Example [1-9][0-9]{0,5}',
    'private_address': r'[1-9][0-9]{0,5} Example Street, Sampletown',
    'private_email': r'person[1-9][0-9]{0,5}\.[0-9a-f]{6}@example\.invalid',
    'private_phone': r'\+1 202 555 01[0-9]{2}',
    'private_date': r'2000-01-(?:0[1-9]|1[0-9]|2[0-8])',
    'private_url': r'https://example\.invalid/reference/[0-9a-f]{6}/[1-9][0-9]{0,5}',
    'account_number': r'DEMO-[0-9A-F]{6}-[0-9]{6}',
    'secret': r'SYNTHETIC-[0-9a-f]{6}-[1-9][0-9]{0,5}',
}


class HistoryMetadata(BaseModel):
    model_config = ConfigDict(extra='forbid')
    source_type: Literal['pdf', 'docx']
    mode: Literal['redact', 'placeholder', 'synthetic']
    sensitivity: int = Field(default=50, ge=0, le=100, multiple_of=5, strict=True)
    counts: dict[str, StrictInt] = Field(default_factory=dict)
    layout_preserved: bool = Field(strict=True)
    warning_codes: list[Literal['images_unscanned', 'layout_fallback', 'ocr_unavailable']] = Field(default_factory=list, max_length=3)
    protection_version: Literal[1, 2] = 1
    replacements: list[PublicReplacement] | None = Field(default=None, max_length=200_000)

    @field_validator('counts')
    @classmethod
    def safe_counts(cls, value):
        if not set(value).issubset(LABELS) or any(type(count) is not int or count < 0 or count > 200_000 for count in value.values()):
            raise ValueError('Invalid detection counts.')
        return value

    @model_validator(mode='after')
    def safe_replacements(self):
        if self.replacements is None:
            return self
        if len(self.replacements) != sum(self.counts.values()):
            raise ValueError('Replacement counts do not match detections.')
        seen = set()
        for item in self.replacements:
            key = (item.category, item.occurrence)
            if item.category not in LABELS or item.occurrence > self.counts.get(item.category, 0) or key in seen:
                raise ValueError('Invalid replacement occurrence.')
            seen.add(key)
            if self.mode == 'redact':
                valid = item.replacement == ('**/**/**' if item.category == 'private_date' else '******')
            elif self.mode == 'placeholder':
                valid = item.replacement == f'[{LABELS[item.category]}]'
            else:
                valid = re.fullmatch(SYNTHETIC_PATTERNS[item.category], item.replacement) is not None
            if not valid:
                raise ValueError('Only generated replacement values may be stored in review metadata.')
        return self


def valid_identifier(identifier):
    try:
        return str(UUID(identifier)) == identifier
    except (ValueError, TypeError):
        return False


class HistoryStore:
    def __init__(self, root: Path, *, clock=time.time):
        self.root, self.path, self.clock = root, root / 'documents.sqlite3', clock
        root.mkdir(parents=True, exist_ok=True, mode=0o700)
        with self.connection() as conn:
            version = conn.execute('PRAGMA user_version').fetchone()[0]
            if version > SCHEMA_VERSION:
                raise RuntimeError('This history database requires a newer application version.')
            # Legacy records have no owner and must never be assigned to a new user.
            legacy = conn.execute("SELECT 1 FROM sqlite_master WHERE type='table' AND name='documents'").fetchone()
            if legacy:
                conn.execute('DROP TABLE documents')
            conn.execute('CREATE TABLE IF NOT EXISTS history_documents ('
                         'id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, created REAL NOT NULL, '
                         "status TEXT NOT NULL CHECK(status IN ('draft','complete')), expires REAL, "
                         'metadata TEXT NOT NULL, protection_version INTEGER NOT NULL)')
            conn.execute('CREATE INDEX IF NOT EXISTS history_owner ON history_documents(owner_id, created)')
            conn.execute('CREATE TABLE IF NOT EXISTS history_artifacts ('
                         'document_id TEXT NOT NULL REFERENCES history_documents(id) ON DELETE CASCADE, '
                         'kind TEXT NOT NULL, payload BLOB NOT NULL, PRIMARY KEY(document_id, kind))')
            conn.execute('CREATE TABLE IF NOT EXISTS history_corrections ('
                         'document_id TEXT PRIMARY KEY REFERENCES history_documents(id) ON DELETE CASCADE, '
                         'payload BLOB NOT NULL, detail_count INTEGER NOT NULL, revision INTEGER NOT NULL, '
                         'updated_by TEXT NOT NULL, updated_at REAL NOT NULL)')
            conn.execute('CREATE TABLE IF NOT EXISTS history_review_audit ('
                         'document_id TEXT NOT NULL REFERENCES history_documents(id) ON DELETE CASCADE, '
                         'revision INTEGER NOT NULL, detail_count INTEGER NOT NULL, updated_by TEXT NOT NULL, updated_at REAL NOT NULL)')
            conn.execute(f'PRAGMA user_version={SCHEMA_VERSION}')
        self.path.chmod(0o600)
        # Legacy UUID output folders are a reserved namespace. Sweep every start
        # so interruption after the schema transaction cannot strand old plaintext.
        for path in root.iterdir():
            if valid_identifier(path.name):
                if path.is_symlink():
                    path.unlink()
                elif path.is_dir():
                    shutil.rmtree(path)
        self.cleanup()

    @contextmanager
    def connection(self):
        conn = sqlite3.connect(self.path, timeout=10)
        conn.row_factory = sqlite3.Row
        conn.execute('PRAGMA foreign_keys=ON')
        conn.execute('PRAGMA secure_delete=ON')
        try:
            with conn:
                yield conn
        finally:
            conn.close()

    @staticmethod
    def owner(owner):
        if not isinstance(owner, VerifiedOwner):
            raise TypeError('History operations require a verified owner.')
        return owner.owner_id

    def cleanup(self):
        with self.connection() as conn:
            conn.execute("DELETE FROM history_documents WHERE status='draft' AND expires<=?", (self.clock(),))

    def _record(self, conn, owner, identifier):
        if not valid_identifier(identifier):
            raise HTTPException(404, 'History document not found.')
        row = conn.execute('SELECT * FROM history_documents WHERE owner_id=? AND id=?', (self.owner(owner), identifier)).fetchone()
        if row is None or (row['status'] == 'draft' and row['expires'] <= self.clock()):
            raise HTTPException(404, 'History document not found.')
        return row

    @staticmethod
    def public(row, correction=None):
        import json
        return {'id': row['id'], 'created': datetime.fromtimestamp(row['created'], timezone.utc).isoformat(),
                'status': row['status'], 'protection_version': row['protection_version'],
                **json.loads(row['metadata']),
                'review_revision': correction['revision'] if correction else 0,
                **({'detail_count': correction['detail_count'], 'reviewed_at': datetime.fromtimestamp(correction['updated_at'], timezone.utc).isoformat()} if correction else {})}

    def create(self, owner, metadata):
        owner_id = self.owner(owner)
        self.cleanup()
        with self.connection() as conn:
            conn.execute('BEGIN IMMEDIATE')
            count = conn.execute('SELECT COUNT(*) FROM history_documents WHERE owner_id=?', (owner_id,)).fetchone()[0]
            if count >= MAX_OWNER_DOCUMENTS:
                raise HTTPException(429, 'History storage is full. Delete a document before saving another.')
            identifier, now = str(uuid4()), self.clock()
            conn.execute('INSERT INTO history_documents VALUES (?,?,?,?,?,?,?)',
                         (identifier, owner_id, now, 'draft', now + DRAFT_TTL, metadata.model_dump_json(), metadata.protection_version))
            return self.public(self._record(conn, owner, identifier))

    def listing(self, owner):
        owner_id = self.owner(owner)
        self.cleanup()
        with self.connection() as conn:
            return [self.public(row, conn.execute('SELECT * FROM history_corrections WHERE document_id=?', (row['id'],)).fetchone()) for row in conn.execute(
                "SELECT * FROM history_documents WHERE owner_id=? AND status='complete' ORDER BY created DESC", (owner_id,))]

    def get(self, owner, identifier):
        with self.connection() as conn:
            return self.public(self._record(conn, owner, identifier), conn.execute('SELECT * FROM history_corrections WHERE document_id=?', (identifier,)).fetchone())

    def correction(self, owner, identifier):
        with self.connection() as conn:
            self._record(conn, owner, identifier)
            row = conn.execute('SELECT payload FROM history_corrections WHERE document_id=?', (identifier,)).fetchone()
            if not row:
                raise HTTPException(404, 'No saved correction.')
            return row['payload']

    def save_correction(self, owner, identifier, payload, detail_count, revision, only_if_missing=False):
        if not owner.can_write:
            raise HTTPException(403, 'This account has read-only access.')
        if not payload or len(payload) > MAX_ARTIFACT:
            raise HTTPException(413, 'Protected correction exceeds the storage limit.')
        if type(detail_count) is not int or not 0 <= detail_count <= 200_000 or type(revision) is not int or revision < 0:
            raise HTTPException(422, 'Invalid correction metadata.')
        with self.connection() as conn:
            conn.execute('BEGIN IMMEDIATE')
            row = self._record(conn, owner, identifier)
            if row['status'] != 'complete':
                raise HTTPException(409, 'Finish saving the document first.')
            old = conn.execute('SELECT * FROM history_corrections WHERE document_id=?', (identifier,)).fetchone()
            if old and only_if_missing:
                return self.public(row, old)
            current = old['revision'] if old else 0
            if revision != current:
                raise HTTPException(409, 'This review changed in another tab. Reopen it before saving.')
            size = conn.execute('SELECT COALESCE(SUM(length(payload)),0) FROM history_artifacts WHERE document_id=?', (identifier,)).fetchone()[0]
            if size + len(payload) > MAX_DOCUMENT:
                raise HTTPException(413, 'Protected document exceeds the storage limit.')
            now = self.clock()
            conn.execute('INSERT INTO history_corrections VALUES (?,?,?,?,?,?) ON CONFLICT(document_id) DO UPDATE SET '
                         'payload=excluded.payload, detail_count=excluded.detail_count, revision=excluded.revision, updated_by=excluded.updated_by, updated_at=excluded.updated_at',
                         (identifier, payload, detail_count, current + 1, self.owner(owner), now))
            conn.execute('INSERT INTO history_review_audit VALUES (?,?,?,?,?)', (identifier, current + 1, detail_count, self.owner(owner), now))
            return self.public(row, {'revision': current + 1, 'detail_count': detail_count, 'updated_at': now})

    def put(self, owner, identifier, kind, payload):
        if kind not in KINDS:
            raise HTTPException(400, 'Unsupported artifact kind.')
        if not payload or len(payload) > MAX_ARTIFACT:
            raise HTTPException(413, 'Protected artifact is empty or exceeds the storage limit.')
        with self.connection() as conn:
            conn.execute('BEGIN IMMEDIATE')
            row = self._record(conn, owner, identifier)
            if row['status'] != 'draft':
                raise HTTPException(409, 'Completed history is immutable. Create a new record.')
            size = conn.execute('SELECT COALESCE(SUM(length(payload)),0) FROM history_artifacts WHERE document_id=? AND kind<>?', (identifier, kind)).fetchone()[0]
            if size + len(payload) > MAX_DOCUMENT:
                raise HTTPException(413, 'Protected document exceeds the storage limit.')
            conn.execute('INSERT INTO history_artifacts VALUES (?,?,?) ON CONFLICT(document_id,kind) DO UPDATE SET payload=excluded.payload',
                         (identifier, kind, payload))

    def artifact(self, owner, identifier, kind):
        with self.connection() as conn:
            self._record(conn, owner, identifier)
            row = conn.execute('SELECT payload FROM history_artifacts WHERE document_id=? AND kind=?', (identifier, kind)).fetchone()
            if row is None:
                raise HTTPException(404, 'Protected artifact not found.')
            return row['payload']

    def commit(self, owner, identifier):
        with self.connection() as conn:
            conn.execute('BEGIN IMMEDIATE')
            row = self._record(conn, owner, identifier)
            kinds = {row[0] for row in conn.execute('SELECT kind FROM history_artifacts WHERE document_id=?', (identifier,))}
            expected = KINDS if row['protection_version'] == 2 else LEGACY_KINDS
            if kinds != expected:
                raise HTTPException(409, 'Upload all protected artifacts before saving history.')
            conn.execute("UPDATE history_documents SET status='complete', expires=NULL WHERE owner_id=? AND id=?", (self.owner(owner), identifier))
            return self.public(self._record(conn, owner, identifier))

    def upgrade_filename(self, owner, identifier, payload):
        """Add a browser-encrypted filename after an explicit legacy reveal."""
        import json
        if not payload or len(payload) > 64 * 1024:
            raise HTTPException(413, 'Protected filename is empty or too large.')
        with self.connection() as conn:
            conn.execute('BEGIN IMMEDIATE')
            row = self._record(conn, owner, identifier)
            if row['status'] != 'complete':
                raise HTTPException(409, 'Finish saving the document first.')
            if row['protection_version'] == 2:
                return self.public(row)
            size = conn.execute('SELECT COALESCE(SUM(length(payload)),0) FROM history_artifacts WHERE document_id=?', (identifier,)).fetchone()[0]
            if size + len(payload) > MAX_DOCUMENT:
                raise HTTPException(413, 'Protected document exceeds the storage limit.')
            conn.execute('INSERT INTO history_artifacts VALUES (?,?,?)', (identifier, 'filename', payload))
            metadata = json.loads(row['metadata']); metadata['protection_version'] = 2
            conn.execute('UPDATE history_documents SET protection_version=2, metadata=? WHERE id=?',
                         (json.dumps(metadata), identifier))
            return self.public(self._record(conn, owner, identifier))

    def add_replacements(self, owner, identifier, projection):
        """Publish generated replacements for an older owned record, once."""
        import json
        with self.connection() as conn:
            conn.execute('BEGIN IMMEDIATE')
            row = self._record(conn, owner, identifier)
            if row['status'] != 'complete':
                raise HTTPException(409, 'Finish saving the document first.')
            metadata = json.loads(row['metadata'])
            try:
                updated = HistoryMetadata(**(metadata | projection.model_dump()))
            except ValidationError:
                raise HTTPException(422, 'Invalid generated replacements.') from None
            if metadata.get('replacements') is None:
                conn.execute('UPDATE history_documents SET metadata=? WHERE id=?',
                             (updated.model_dump_json(), identifier))
            return self.public(self._record(conn, owner, identifier))

    def delete(self, owner, identifier):
        with self.connection() as conn:
            conn.execute('BEGIN IMMEDIATE')
            self._record(conn, owner, identifier)
            conn.execute('DELETE FROM history_documents WHERE owner_id=? AND id=?', (self.owner(owner), identifier))
