// UI smoke test with an explicit fixture API; backend tests exercise actual files.
import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1150 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
let docs = [];
const csrfToken = 'fixture-csrf-token';
const uploadName = 'Sample report – résumé.pdf';
await page.route('**/api/service/**', async route => {
  const request = route.request();
  const url = new URL(request.url());
  let body;
  if (url.pathname.endsWith('/capabilities')) body = { secure_history: { available: false, reason: 'Secure history is not configured.' } };
  else if (url.pathname.endsWith('/health')) body = { model_installed: true, model_loaded: false, device: 'cpu' };
  else if (request.method() === 'POST') {
    assert.equal(url.pathname, '/api/service/guest/documents');
    assert.equal(request.headers()['x-csrf-token'], csrfToken);
    assert.equal(request.headers()['x-document-name'], encodeURIComponent(uploadName));
    assert.equal(url.searchParams.get('mode'), 'synthetic');
    assert.equal(url.searchParams.get('type'), '.pdf');
    assert.equal(url.searchParams.get('sensitivity'), '75');
    assert.equal(request.postDataBuffer().toString(), '%PDF-fixture');
    docs = [{ id: '11111111-1111-4111-8111-111111111111', created: new Date().toISOString(), filename: uploadName, mode: 'synthetic', sensitivity: 75, status: 'processing', counts: { private_person: 2 } }];
    body = { id: docs[0].id };
  } else if (request.method() === 'DELETE') { assert.equal(request.headers()['x-csrf-token'], csrfToken); docs = []; body = { deleted: true }; }
  else if (url.pathname.endsWith('/preview')) body = { text: 'Alex Example 1 contacted Alex Example 1.' };
  else if (url.pathname.endsWith('/guest/current')) body = { document: docs[0] || null, csrf_token: csrfToken, expires_at: null };
  else throw new Error(`Unexpected API request: ${url.pathname}`);
  await route.fulfill({ json: body });
});
try {
  await page.goto(process.env.BASE_URL || 'http://127.0.0.1:4173');
  await page.getByText('No files yet.').waitFor();
  await mkdir('artifacts', { recursive: true });
  const redactButton = page.getByRole('button', { name: 'REDACT', exact: true });
  assert.equal(await redactButton.isDisabled(), true);
  await redactButton.hover();
  assert.equal(await page.locator('.redact-label').innerText(), 'REDACT');
  assert.equal(await page.getByText('ADD A FILE TO REDACT', { exact: true }).count(), 0);
  await page.locator('.redact-arrow').evaluate(el => Promise.all(el.getAnimations().map(animation => animation.finished)));
  assert.equal(await page.locator('.redact-arrow').evaluate(el => Math.round(new DOMMatrix(getComputedStyle(el).transform).b)), -1);
  await page.screenshot({ path: 'artifacts/upload-hint.png', fullPage: true });
  await page.locator('.brand').hover();
  assert.equal(await page.locator('.redact-file-hint').count(), 0);
  await page.screenshot({ path: 'artifacts/desktop.png', fullPage: true });
  assert.equal(await page.getByRole('button', { name: 'Settings', exact: true }).getAttribute('aria-expanded'), 'false');
  assert.equal(await page.locator('#upload-settings').isVisible(), false);
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  assert.equal(await page.getByRole('radio', { name: 'Mask', exact: true }).isChecked(), true);
  await page.getByRole('radio', { name: 'Label', exact: true }).check();
  assert.equal(await page.getByRole('slider', { name: 'Sensitivity', exact: true }).inputValue(), '50');
  await page.getByRole('button', { name: 'About redaction modes', exact: true }).click();
  await page.getByRole('tooltip').waitFor();
  assert.match(await page.getByRole('tooltip').innerText(), /labels like/);
  await page.keyboard.press('Escape');
  assert.equal(await page.getByRole('tooltip').count(), 0);
  await page.getByRole('button', { name: 'About redaction modes', exact: true }).click();
  assert.match(await page.getByRole('tooltip').innerText(), /fictional data/);
  await page.getByRole('radio', { name: 'Replace', exact: true }).check();
  assert.equal(await page.getByRole('tooltip').count(), 0);
  await page.getByRole('slider', { name: 'Sensitivity', exact: true }).fill('75');
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  assert.equal(await page.locator('#upload-settings').isVisible(), false);
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  assert.equal(await page.getByRole('radio', { name: 'Replace', exact: true }).isChecked(), true);
  assert.equal(await page.getByRole('slider', { name: 'Sensitivity', exact: true }).inputValue(), '75');
  await page.screenshot({ path: 'artifacts/settings.png', fullPage: true });
  await page.locator('input[type=file]').setInputFiles({ name: uploadName, mimeType: 'application/pdf', buffer: Buffer.from('%PDF-fixture') });
  await redactButton.hover();
  assert.equal(await page.locator('.redact-file-hint').count(), 0);
  assert.equal(await page.locator('.redact-label').isVisible(), true);
  await redactButton.click();
  await page.locator('.document-name.is-processing .redaction-loader').waitFor();
  assert.match(await page.locator('.document-name.is-processing').innerText(), /Sample report – résumé\.pdf/);
  assert.equal(await page.locator('.redaction-loader').evaluate(el => getComputedStyle(el).animationName), 'redaction-sweep');
  assert.equal(await page.locator('.processing-ring').count(), 0);
  await page.screenshot({ path: 'artifacts/processing.png', fullPage: true });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  assert.equal(await page.locator('.redaction-loader').evaluate(el => getComputedStyle(el).animationName), 'none');
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  docs[0].status = 'complete';
  docs[0].source_type = 'pdf';
  docs[0].layout_preserved = false;
  docs[0].warning = 'Images are preserved but are not scanned for sensitive data. Original layout unavailable; clean rewrite used.';
  await page.getByText('2 names', { exact: true }).waitFor();
  assert.equal(await page.locator('.redaction-loader').count(), 0);
  assert.equal(await page.getByText(uploadName, { exact: true }).count(), 1);
  assert.match(await page.locator('.mode-pill').first().innerText(), /Replaced/);
  await page.getByText('Original layout unavailable; clean rewrite used.').waitFor();
  assert.equal(await page.locator('.document-row .doc-warning').innerText(), 'Original layout unavailable; clean rewrite used.');
  assert.equal(await page.locator('.document-row').getByText('Images are preserved but are not scanned for sensitive data.', { exact: false }).count(), 0);
  assert.equal(await page.getByRole('link', { name: /Download PDF/ }).getAttribute('title'), 'Rebuilt text');
  assert.equal(await page.getByText('complete', { exact: true }).count(), 0);
  await page.getByRole('button', { name: 'Preview', exact: true }).click();
  await page.getByText('Alex Example 1 contacted Alex Example 1.', { exact: true }).waitFor();
  await page.keyboard.press('Escape');
  page.once('dialog', async dialog => {
    assert.equal(dialog.message(), 'Are you sure you want to trash this file?');
    await dialog.dismiss();
  });
  await page.getByRole('button', { name: /Delete document/ }).click();
  assert.equal(docs.length, 1);
  assert.equal(await page.locator('.document-row').count(), 1);
  page.once('dialog', async dialog => {
    assert.equal(dialog.message(), 'Are you sure you want to trash this file?');
    await dialog.accept();
  });
  await page.getByRole('button', { name: /Delete document/ }).click();
  await page.getByText('No files yet.').waitFor();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'About redaction modes', exact: true }).click();
  await page.screenshot({ path: 'artifacts/mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false);
  assert.deepEqual(errors, []);
  console.log('Browser smoke passed: encoded filename, filename redaction loader, reduced motion, unchanged REDACT hover label, modes, counts, preview, deletion and mobile layout.');
} finally { await browser.close(); }
